SUPABASE_URL = "https://uphjhkhdpsqbnmxfysjg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaGpoa2hkcHNxYm5teGZ5c2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MTkwMDcsImV4cCI6MjA5NDA5NTAwN30.sscUY8yXv9gCq3uoLH_hJxrfPml3mVBNUaCtQyCunMA"
