# const firebaseConfig = {
#   apiKey: "AIzaSyXXXX...",
#   authDomain: "cruncherx.firebaseapp.com",
#   projectId: "cruncherx",
#   storageBucket: "cruncherx.appspot.com",
#   messagingSenderId: "1234567890",
#   appId: "1:1234567890:web:abcdef123456"
# };

SUPABASE_URL = "https://YOUR-PROJECT-ID.supabase.co"
SUPABASE_KEY = "YOUR-ANON-KEY"

SUPABASE_URL = https://uphjhkhdpsqbnmxfysjg.supabase.co
SUPABASE_KEY = sb_publishable_W1bJpOd0Y-hPF0wqm9wQSg_egy6e1w7
